# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Install any needed packages specified in requirements.txt
RUN pip install flask requests

# Copy the current directory contents into the container at /app
COPY . /app

# Make port 8082 available to the world outside this container
EXPOSE 8082

# Run app.py when the container launches
CMD ["python", "app3.py"]
